title: Shreedhar Govil
description: Personal website of Shreedhar Govil
url: "https://sdhar16.github.io" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: pmarsceill/just-the-docs
permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search
search_enabled: false

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "//github.com/sdhar16/"
  "Linkedin":
    - https://in.linkedin.com/in/shreedhar-govil-891581132?trk=profile-badge-name
